
name: Continuous integration

concurrency:
  group: ${{ github.head_ref }}${{ github.ref }}-wallet-sdk
  cancel-in-progress: true
on:
  pull_request:
    branches:
      - 'main'
      - 'release/*'
  push:
    branches:
      - 'main'
      - 'release/*'


jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'true' 

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install wasm-pack
        run: |
          curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
          
      - name: Install
        run: npm install && npm i @rollup/rollup-linux-x64-gnu

      - name: Eslint
        run: npx eslint .

      - name: Build
        run: npm run build

      - name: Run coverage test
        run: npm run coverage

      - name: Npm audit
        uses: oke-py/npm-audit-action@v2.4.4
        with:
          audit_level: moderate
          create_issues: false
          github_token: ${{ secrets.GITHUB_TOKEN }}
          production_flag: true

      - name: Coveralls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: coverallsapp/github-action@v2
        with:
          file: "coverage/lcov.info"

      - name: Jest Coverage Comment
        uses: MishaKav/jest-coverage-comment@v1.0.23
        with:
          coverage-summary-path: coverage/coverage-summary.json
          junitxml-path: coverage/junit.xml
          junitxml-title: JUnit

      - name: Publish lcov report
        uses: actions/upload-artifact@v3
        with:
          name: lcov-report.zip
          path: coverage/lcov-report
          if-no-files-found: error
